AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Well-Architected Security MCP Server - Production Security (Level 2)

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues: [dev, prod]
    Description: Deployment environment (dev/prod)
  
  NotificationEmail:
    Type: String
    Description: Email address to receive critical security findings
    Default: joewebacc@gmail.com
  
  EnableBedrock:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
    Description: Enable Amazon Bedrock for AI-powered executive summaries

Resources:
  # =============================================================================
  # SECURITY: Secrets Manager for sensitive configuration
  # =============================================================================
  MCPSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AWS::StackName}/config'
      Description: Configuration secrets for MCP Security Server
      SecretString: !Sub |
        {
          "notification_email": "${NotificationEmail}"
        }

  # =============================================================================
  # SECURITY: KMS Key for Lambda environment variable encryption
  # =============================================================================
  LambdaKmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS key for Lambda environment variables encryption
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow Lambda to decrypt
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - 'kms:Decrypt'
              - 'kms:DescribeKey'
            Resource: '*'
            Condition:
              StringEquals:
                'kms:ViaService': !Sub 'lambda.${AWS::Region}.amazonaws.com'

  LambdaKmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/${AWS::StackName}-lambda'
      TargetKeyId: !Ref LambdaKmsKey

  # =============================================================================
  # SNS Topic for Critical Findings
  # =============================================================================
  SecurityNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub 'security-mcp-notifications-${Environment}'
      DisplayName: AWS Security MCP Critical Findings
      Subscription:
        - Endpoint: !Ref NotificationEmail
          Protocol: email

  # =============================================================================
  # SECURITY: Enhanced IAM Role with resource-scoped permissions
  # =============================================================================
  MCPLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        # SECURITY: Read-only security assessment permissions
        - PolicyName: ReadOnlySecurityAssessment
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # GuardDuty - scoped to detectors in this account/region
              - Effect: Allow
                Action:
                  - guardduty:Get*
                  - guardduty:List*
                Resource: !Sub 'arn:aws:guardduty:${AWS::Region}:${AWS::AccountId}:detector/*'
              
              # Security Hub - scoped to hub in this account/region
              - Effect: Allow
                Action:
                  - securityhub:Get*
                  - securityhub:List*
                  - securityhub:Describe*
                Resource: !Sub 'arn:aws:securityhub:${AWS::Region}:${AWS::AccountId}:hub/default'
              
              # CloudTrail - describe operations
              - Effect: Allow
                Action:
                  - cloudtrail:Describe*
                  - cloudtrail:Get*
                  - cloudtrail:List*
                Resource: '*'
                Condition:
                  StringEquals:
                    'aws:RequestedRegion': !Ref AWS::Region
              
              # KMS - scoped to keys in this account/region
              - Effect: Allow
                Action:
                  - kms:List*
                  - kms:Describe*
                  - kms:GetKeyRotationStatus
                Resource: !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*'
              
              # S3 - read bucket metadata only
              - Effect: Allow
                Action:
                  - s3:GetBucket*
                  - s3:ListAllMyBuckets
                  - s3:GetAccountPublicAccessBlock
                Resource: '*'
              
              # IAM - read-only
              - Effect: Allow
                Action:
                  - iam:GetAccountSummary
                  - iam:GetAccountPasswordPolicy
                  - iam:ListUsers
                  - iam:ListAccessKeys
                  - iam:GetUser
                Resource: '*'
              
              # EC2 - describe only
              - Effect: Allow
                Action:
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeNetworkAcls
                  - ec2:DescribeFlowLogs
                  - ec2:DescribeInstances
                Resource: '*'
                Condition:
                  StringEquals:
                    'aws:RequestedRegion': !Ref AWS::Region
              
              # Config - read configuration
              - Effect: Allow
                Action:
                  - config:Describe*
                  - config:Get*
                  - config:List*
                Resource: '*'
        
        # SECURITY: SNS publish scoped to specific topic only
        - PolicyName: SNSPublish
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref SecurityNotificationTopic
        
        # SECURITY: Bedrock invoke scoped to specific model
        - PolicyName: BedrockInvoke
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/amazon.nova-pro-v1:0'
                Condition:
                  StringEquals:
                    'aws:RequestedRegion': !Ref AWS::Region
        
        # SECURITY: Secrets Manager read access
        - PolicyName: SecretsManagerRead
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref MCPSecrets
        
        # SECURITY: KMS decrypt for environment variables
        - PolicyName: KMSDecrypt
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:DescribeKey
                Resource: !GetAtt LambdaKmsKey.Arn

  # =============================================================================
  # SECURITY: API Gateway with API Key Authentication
  # =============================================================================
  MCPApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      TracingEnabled: true
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: MCP Security Server usage plan with rate limiting
          Quota:
            Limit: 1000
            Period: DAY
          Throttle:
            BurstLimit: 50
            RateLimit: 10
      AccessLogSetting:
        DestinationArn: !GetAtt ApiGatewayLogGroup.Arn
        Format: '$context.requestId $context.identity.sourceIp $context.identity.caller $context.identity.user [$context.requestTime] "$context.httpMethod $context.resourcePath $context.protocol" $context.status $context.responseLength $context.error.message'
      MethodSettings:
        - ResourcePath: '/*'
          HttpMethod: '*'
          LoggingLevel: INFO
          DataTraceEnabled: true
          MetricsEnabled: true

  # =============================================================================
  # SECURITY: CloudWatch Log Group for API Gateway
  # =============================================================================
  ApiGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/apigateway/${AWS::StackName}'
      RetentionInDays: 30

  # =============================================================================
  # Lambda Function with enhanced security
  # =============================================================================
  MCPServerLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'mcp-security-server-${Environment}'
      Handler: lambda_handler.handler
      Runtime: python3.12
      CodeUri: src/
      Role: !GetAtt MCPLambdaRole.Arn
      Timeout: 120
      MemorySize: 512
      KmsKeyArn: !GetAtt LambdaKmsKey.Arn
      Environment:
        Variables:
          LOG_LEVEL: INFO
          SNS_TOPIC_ARN: !Ref SecurityNotificationTopic
          SECRETS_ARN: !Ref MCPSecrets
          ENABLE_BEDROCK: !Ref EnableBedrock
      Tracing: Active
      Events:
        HealthCheck:
          Type: Api
          Properties:
            RestApiId: !Ref MCPApiGateway
            Path: /health
            Method: GET
            Auth:
              ApiKeyRequired: true
        Assessment:
          Type: Api
          Properties:
            RestApiId: !Ref MCPApiGateway
            Path: /assess
            Method: POST
            Auth:
              ApiKeyRequired: true

  # =============================================================================
  # Scheduled Assessment Rule (Daily at 9 AM UTC)
  # =============================================================================
  DailyAssessmentRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Run security assessment daily at 9 AM UTC
      ScheduleExpression: cron(0 9 * * ? *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt MCPServerLambda.Arn
          Id: DailySecurityAssessment
          Input: |
            {
              "body": "{\"region\": \"us-east-1\", \"focus_areas\": [\"IAM\", \"Logging\", \"Network\", \"Storage\", \"Encryption\", \"ThreatDetection\"], \"send_notifications\": true}"
            }

  DailyAssessmentPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref MCPServerLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt DailyAssessmentRule.Arn

  # =============================================================================
  # SECURITY: CloudWatch Alarms for monitoring
  # =============================================================================
  HighErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AWS::StackName}-high-error-rate'
      AlarmDescription: Alert when Lambda error rate exceeds threshold
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref MCPServerLambda
      TreatMissingData: notBreaching

  UnauthorizedAccessAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AWS::StackName}-unauthorized-access'
      AlarmDescription: Alert on high number of 403 errors
      MetricName: 4XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 50
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Ref MCPApiGateway
        - Name: Stage
          Value: prod
      TreatMissingData: notBreaching

# =============================================================================
# Outputs
# =============================================================================
Outputs:
  LambdaArn:
    Description: ARN of the Lambda function
    Value: !GetAtt MCPServerLambda.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaArn'
  
  ApiEndpoint:
    Description: URL to invoke the MCP server (requires x-api-key header)
    Value: !Sub 'https://${MCPApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod'
    Export:
      Name: !Sub '${AWS::StackName}-ApiEndpoint'
  
  SNSTopicArn:
    Description: ARN of the SNS topic for notifications
    Value: !Ref SecurityNotificationTopic
    Export:
      Name: !Sub '${AWS::StackName}-SNSTopicArn'
  
  SecretsArn:
    Description: ARN of the Secrets Manager secret
    Value: !Ref MCPSecrets
    Export:
      Name: !Sub '${AWS::StackName}-SecretsArn'
  
  KmsKeyArn:
    Description: ARN of the KMS key for Lambda encryption
    Value: !GetAtt LambdaKmsKey.Arn
    Export:
      Name: !Sub '${AWS::StackName}-KmsKeyArn'
  
  GetApiKeyCommand:
    Description: Run this command to get your API key
    Value: !Sub |
      aws apigateway get-api-keys --include-values --query 'items[?name==`${AWS::StackName}-api-key`].value' --output text
