AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Well-Architected Security MCP Server - Lambda + API Gateway

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]

Resources:
  # IAM Role - Least Privilege (read-only for security services)
  MCPLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ReadOnlySecurityAssessment
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - guardduty:Get*
                  - guardduty:List*
                  - securityhub:Get*
                  - securityhub:List*
                  - securityhub:Describe*
                  - inspector2:Get*
                  - inspector2:List*
                  - accessanalyzer:List*
                  - accessanalyzer:Get*
                  - macie2:List*
                  - macie2:Get*
                  - iam:Get*
                  - iam:List*
                  - cloudtrail:Get*
                  - config:Get*
                  - ec2:Describe*
                  - s3:GetBucket*
                  - s3:List*
                  - kms:Describe*
                  - kms:Get*
                  - kms:List*
                Resource: '*'

  # Lambda Function (MCP Server)
  MCPServerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'mcp-security-server-${Environment}'
      Handler: main.handler
      Runtime: python3.12
      Role: !GetAtt MCPLambdaRole.Arn
      Timeout: 60
      MemorySize: 512
      Environment:
        Variables:
          LOG_LEVEL: INFO

  # API Gateway (expose MCP endpoints)
  MCPApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub 'MCP-Security-API-${Environment}'
      Description: API for AWS Security MCP Server

  # Outputs
Outputs:
  LambdaArn:
    Value: !GetAtt MCPServerLambda.Arn
  ApiEndpoint:
    Value: !Sub 'https://${MCPApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod'